import { ROLES } from '@/utils/constants';

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

export const USER_MANAGEMENT_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.IT_SUPPORT, ROLES.IT_MANAGER
];

export const PURCHASING_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PURCHASING_MANAGER, ROLES.PURCHASING_STAFF
];

export const MANAGER_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.IT_MANAGER,
  ROLES.OPERATIONS_MANAGER, ROLES.PURCHASING_MANAGER, ROLES.ACCOUNTS_MANAGER,
  ROLES.SAFETY_MANAGER, ROLES.MAINTENANCE_MANAGER,
  ROLES.HR_MANAGER, ROLES.LOGISTICS_MANAGER, ROLES.WORKSHOP_MANAGER
];

export const EQUIPMENT_MANAGER_ROLES = [...MANAGER_ROLES, ROLES.PURCHASING_STAFF];

export const MAINTENANCE_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.IT_SUPPORT, ROLES.IT_MANAGER,
  ROLES.OPERATIONS_MANAGER, ROLES.MAINTENANCE_MANAGER, ROLES.FIELD_ENGINEER,
  ROLES.PURCHASING_MANAGER, ROLES.PURCHASING_STAFF,
  ROLES.ACCOUNTS_MANAGER, ROLES.ACCOUNTS_STAFF,
  ROLES.HR_MANAGER, ROLES.LOGISTICS_MANAGER, ROLES.WORKSHOP_MANAGER
];

export const ACCOUNTS_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTS_MANAGER, ROLES.ACCOUNTS_STAFF
];

export const SAFETY_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SAFETY_OFFICER, ROLES.SAFETY_MANAGER,
  ROLES.OPERATIONS_MANAGER
];

export const DEV_PREVIEW_ROLES = [ROLES.SUPER_ADMIN];
